### PR TITLE
[WIP] Update util.go

### PR DESCRIPTION
**Pull request by dims**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by dims** [comment]
recheck

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-unittest http://80.158.20.68/logs/10/10/ed189cf911183d48a9fe9183db1e014096ade5fb/check/gophercloud-unittest/1ff453b/ : SUCCESS in 2m 05s
- gophercloud-acceptance-test http://80.158.20.68/logs/10/10/ed189cf911183d48a9fe9183db1e014096ade5fb/check/gophercloud-acceptance-test/b9a01e4/ : SUCCESS in 28m 06s

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-acceptance-test-pike http://80.158.20.68/logs/10/10/ed189cf911183d48a9fe9183db1e014096ade5fb/recheck-pike/gophercloud-acceptance-test-pike/a94d467/ : SUCCESS in 26m 44s

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-acceptance-test-mitaka http://80.158.20.68/logs/10/10/ed189cf911183d48a9fe9183db1e014096ade5fb/recheck-mitaka/gophercloud-acceptance-test-mitaka/aec3765/ : SUCCESS in 24m 37s

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
Close the test PR.

**Pull request closed without merging**
