### PR TITLE
Fix the internal path for theopenlab

### PR DESCRIPTION
**Pull request by yongfengdu**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/66cf452/ : SUCCESS in 3m 19s
- gophercloud-acceptance-test http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acceptance-test/828b051/ : FAILURE in 34m 45s

**Comment by kiwik** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/de97c6e/ : SUCCESS in 3m 11s
- gophercloud-acceptance-test http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acceptance-test/d5868af/ : FAILURE in 33m 46s

**Comment by yongfengdu** [comment]
recheck

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/8794b2a/ : FAILURE in 1m 13s
- gophercloud-acctest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acctest/d22c5d0/ : FAILURE in 26m 31s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/29758d9/ : FAILURE in 1m 17s
- gophercloud-acctest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acctest/5ccd03c/ : FAILURE in 26m 08s

**Comment by yongfengdu** [comment]
recheck

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/6726f47/ : FAILURE in 1m 16s
- gophercloud-acctest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acctest/eb24415/ : FAILURE in 26m 20s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/5a83b5c/ : SUCCESS in 2m 11s
- gophercloud-acctest gophercloud-acctest : NODE_FAILURE

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest gophercloud-unittest : NODE_FAILURE
- gophercloud-acctest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acctest/80e953d/ : FAILURE in 26m 06s

**Comment by yongfengdu** [comment]
recheck

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/9aea1ae/ : SUCCESS in 2m 15s
- gophercloud-acctest gophercloud-acctest : ERROR Unable to find playbook /var/lib/zuul/builds/bc3193d6634f467d8601e19372314e81/trusted/project_2/github.com/theopenlab/openlab-zuul-jobs/playbooks/acctest/run

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/963044e/ : SUCCESS in 2m 18s
- gophercloud-acctest gophercloud-acctest : ERROR Unable to find playbook /var/lib/zuul/builds/03a26344a2904fc99fcb3a7ae7065961/trusted/project_2/github.com/theopenlab/openlab-zuul-jobs/playbooks/acctest/run

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest gophercloud-unittest : NODE_FAILURE
- gophercloud-acceptance-test http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-acceptance-test/3f5d3fd/ : TIMED_OUT in 1h 25m 20s

**Comment by yongfengdu** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-acceptance-test-pike gophercloud-acceptance-test-pike : NODE_FAILURE

**Comment by yongfengdu** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-acceptance-test-pike http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/recheck-pike/gophercloud-acceptance-test-pike/2ee252c/ : TIMED_OUT in 1h 24m 44s

**Comment by yongfengdu** [comment]
recheck

**Comment by yongfengdu** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/check/gophercloud-unittest/28d8839/ : SUCCESS in 2m 13s
- gophercloud-acceptance-test gophercloud-acceptance-test : NODE_FAILURE

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-acceptance-test-pike gophercloud-acceptance-test-pike : NODE_FAILURE

**Comment by liu-sheng** [comment]
Hi yongfengdu,

I have added workaround[1] in the openlab-zuul-jobs repo for this path problem, and the unit tests can be passed. see[2]

[1] https://github.com/theopenlab/openlab-zuul-jobs/commit/d305ccf67aecec1e71a77172754680f6c051e294#diff-ff96b6c912a045fb31b289fbe5cce2fc

[2] http://80.158.20.68/logs/5/5/3a173240e5d1ca246990330d1176361fc8161a6b/check/gophercloud-unittest/ce14649/job-output.txt.gz

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-acceptance-test-pike http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/recheck-pike/gophercloud-acceptance-test-pike/6785bcc/ : SUCCESS in 27m 09s

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
Build succeeded.

- gophercloud-acceptance-test-pike http://80.158.20.68/logs/8/8/a15a3adb1d1c37522b316ef137f5bb48b1c74ed8/recheck-pike/gophercloud-acceptance-test-pike/38e220f/ : SUCCESS in 28m 46s

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
Close the test PR.

**Pull request closed without merging**
