### PR TITLE
PR for testing

### PR DESCRIPTION
**Pull request by liu-sheng**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

---
This change is [Reviewable](https://reviewable.io/reviews/theopenlab/gophercloud/19)

### CODE REVIEW

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by liu-sheng** [comment]
recheck telefonica

**Comment by kiwik** [comment]
recheck

**Pull request closed without merging**
