### PR TITLE
Update util_test.go

### PR DESCRIPTION
**Pull request by yongfengdu**
test

### CODE REVIEW

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest finger://openlab-cicd-zuul/c9ca5e52b4834f96b5670dc68b336fe3 : POST_FAILURE in 3m 14s
- gophercloud-acceptance-test finger://openlab-cicd-zuul/671784df0d1b4eaaa1f857e2d1d5213c : POST_FAILURE in 39m 12s

**Comment by animationzl** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest gophercloud-unittest : NODE_FAILURE
- gophercloud-acceptance-test gophercloud-acceptance-test : NODE_FAILURE

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/253bb1f/ : FAILURE in 2m 42s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/ef049ff/ : FAILURE in 39m 18s

**Comment by kiwik** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/c0572a2/ : FAILURE in 2m 49s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/2c2a77d/ : FAILURE in 40m 22s

**Comment by yongfengdu** [comment]
recheck

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/bbe5d52/ : SUCCESS in 2m 59s
- gophercloud-acceptance-test gophercloud-acceptance-test : NODE_FAILURE

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/9b7a17b/ : SUCCESS in 2m 59s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/3fa20ea/ : RETRY_LIMIT in 20s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/05c7c50/ : SUCCESS in 2m 53s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/7aac415/ : FAILURE in 46m 16s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/57b6dba/ : SUCCESS in 3m 00s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/70f9bd3/ : FAILURE in 43m 18s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/4b3861e/ : SUCCESS in 2m 53s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/a2a7d2c/ : FAILURE in 34m 52s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/58d0553/ : SUCCESS in 2m 57s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/473918b/ : RETRY_LIMIT in 20s

**Comment by yongfengdu** [comment]
recheck

**Comment by mrhillsman** [comment]
Build failed.

- gophercloud-unittest http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-unittest/a7abd34/ : FAILURE in 2m 55s
- gophercloud-acceptance-test http://80.158.20.68/logs/6/6/26d3245e5999aa319119178be4a330c32fbd7d1a/check/gophercloud-acceptance-test/4603957/ : FAILURE in 33m 50s

**Pull request closed without merging**
