### PR TITLE
validate cicd's functionality

### PR DESCRIPTION
**Pull request by animationzl**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

**Comment by animationzl** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck
recheck stable/mitaka
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck mitaka

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/ocata

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck stable/ocata

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck stable/ocata

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck stable/ocata

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck stable/mitaka

**Comment by mrhillsman** [comment]
recheck stable/newton

**Comment by mrhillsman** [comment]
recheck stable/ocata

**Comment by mrhillsman** [comment]
recheck stable/pike

**Comment by mrhillsman** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck stable/pike

**Comment by animationzl** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Pull request closed without merging**
