### PR TITLE
test newton ocata jobs

### PR DESCRIPTION
**Pull request by animationzl**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

---
This change is [Reviewable](https://reviewable.io/reviews/theopenlab/gophercloud/13)

### CODE REVIEW

**Comment by animationzl** [comment]
recheck stable/newton

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
stable/newton and stable/ocata had been support in master branch, you can test them in any PR.

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck stable/mitaka

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck stable/pike

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by kiwik** [comment]
recheck stable/newton

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by animationzl** [comment]
recheck stable/ocata

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
newton and ocata support had been merged.

**Pull request closed without merging**
