### PR TITLE
optimize performance with full cache repos

### PR DESCRIPTION
**Pull request by animationzl**
Prior to a PR being reviewed, there needs to be a Github issue that the PR
addresses. Replace the brackets and text below with that issue number.

For #[PUT ISSUE NUMBER HERE]

Links to the line numbers/files in the OpenStack source code that support the
code in this PR:

[PUT URLS HERE]

### CODE REVIEW

**Comment by animationzl** [comment]
recheck

**Comment by liu-sheng** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Comment by kiwik** [comment]
recheck

**Pull request closed without merging**
